spring.application.name=gestion_retos

# Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/challenge_management
spring.datasource.username=postgres
spring.datasource.password=admin

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

# Optional (to see SQL on console)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true